### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by nathanafox-us** [nathanafox-us/foxy-sensors#2]
## New Feature
The users will want to login. We will use their login to control which devices they can see. To accomplish this, we will use AWS Cognito and the AWS Authenticator library.

Since we have to set up a cognito user pool, it will be best to define the private variables they will need before making it:
- [x] key for DDB (holds the sensor names that you have access to)
- [x] name

## Todo:
- [x] The user is given the option to login or register
- [x] They can register with their social media or their email
- [x] The user is only directed to the main page of the app once they are authenticated
