### ISSUE TITLE
Buy More Sensors Button

### ISSUE THREAD

**Issue by nathanafox-us** [nathanafox-us/foxy-sensors#21]
## New Feature
A new button at the bottom of the SensorListPage(...) that sends the user to a website to buy other sensors that work with this app. 

## Why
We want to streamline the process of buying more. I have a feeling if this app ever gets any customers, they will become repeat customers and attempt to stay within the 'Foxy' ecosystem.

## Todo:
- [ ] There is a new AddCard(...)
   - [ ] First asks if the user wants to navigate away from the app
   - [ ] If the user presses yes, the website is opened up where they can purchase other devices that work with the app
