### ISSUE TITLE
Multiple Themes

### ISSUE THREAD

**Issue by nathanafox-us** [nathanafox-us/foxy-sensors#28]
## New Feature
Lets give the user the ability to change the theme of their app if they would like. They can have the option between three different color pallates:

- green
- purple
- orange

## Why
This allows the user to set whatever color scheme is more comfortable for them.

## Todo:
- [ ] Create the const colors to swap between
- [ ] Put a theme selection on the account page
- [ ] Store their selection locally on the machine
