### ISSUE TITLE
HTTP Requests Don't Work On Web

### ISSUE THREAD

**Issue by nathanafox-us** [nathanafox-us/foxy-sensors#31]
## Bug
The HTTP request to AWS does not currently work on the web. The solution to this involves updating the import to conditionally import the web supported HTTP package ```if (kIsWeb)```.

## Security Rating
0/3

## Todo:
- [ ] Package is conditionally imported
- [ ] HTTP/MQTT Requests work on web
- [ ] Functionality is preserved on mobile

**Comment by nathanafox-us** [comment]
I also had to enable CORS on all of the resources in the API Gateway to get the HTTP to work. It is actually the MQTT that requires the conditional import!!
