### ISSUE TITLE
Add/ Remove Sensors Functionality

### ISSUE THREAD

**Issue by nathanafox-us** [nathanafox-us/foxy-sensors#4]
## New Feature
The user needs to be able to add and remove sensors from their list of sensors. Let's have the options be in the dropdown menu when the user is on the sensors list page.

The options will open dialog boxes that help the user provision the device. The user will have the option to tap or use a QR code to retrieve the device code.

The sensors have little security and can be added to multiple lists. The user can only add the sensor to their list one time though, and attempting to add it again will 'fail.'

## Todo:
- [x] There are options in the hamburger menu for 'Add a sensor' and 'Remove a sensor'
- [x] These options pop up dialogs
- [x] The add dialog gives the option to use NFC or QR Code (lets put in a manual entry for debug ONLY FOR NOW!!)
   - [x] IF THE CODE IS ALREADY IN YOUR LIST, FAILS TO ADD!
   - [x] Upon successfully reading the code, it asks the user to create a display name for the sensor
- [x] The remove dialog asks you to select from a list of sensors which sensor you want to remove from the list
   - [x] Upon selection, it asks the user to type the phrase 'please remove sensor' to remove the sensor from the list
