### ISSUE TITLE
Default Sensor View

### ISSUE THREAD

**Issue by nathanafox-us** [nathanafox-us/foxy-sensors#5]
## New Feature
If the sensor does not load correctly (I.e. the app is not updated or something uncontrollable occurred), the user will need some way of knowing. Lets create a ```DefaultSensorCard(...)``` for displaying sensors with a type that does not read correctly.

This card just displays the information in the shadow as a list of attributes and values. It also alerts the user that there may be some misconfiguration occurring. 

Extra credit: it would be really cool if we could set it up to report if it is misconfigured on the user side or the app side, but that seems a little too good to be true.

## Todo:
- [ ] DefaultSensorCard(...) class for displaying a sensor who's type is not being handled yet
- [ ] The card displays that it may be a misconfigured sensor
- [ ] The DefaultSensorDetailPage(...) displays all the information held within the shadow as a list of attributes and values
