### ISSUE TITLE
FacePlantCard(...)

### ISSUE THREAD

**Issue by nathanafox-us** [nathanafox-us/foxy-sensors#6]
## New Feature
The first device we are going to add is the FacePlant sensor. This sensor has 2 readings:
``` 
'state': {
    'reported': {
        'data': {
            'capac': double;
            'temp': double;
        }
    }
} 
```

The capacitance reading goes between 200 (no water) - 2000 (lots of water). Let's display a happy face that evenly cuts this to start (maybe we will give the user the option to change this later), and display an indicator of the capacitance value in the range (progress bar).

For now, we will report the temperature but IGNORE IT when calculating the smiley face. Since the reading is there, we may include it later.

## Todo:
- [x] FacePlantCard(...) shows smiley face level and name of device
- [x] Clicking on FacePlantCard(...) takes you to the FacePlantDetailPage(...)
- [x] The FacePlantDetailPage(...) shows
   - [x] Smiley face
   - [x] Name
   - [x] Hydration Range
   - [x] Temperature
   - [x] Last Reported Date
