### ISSUE TITLE
AccountDetailPage(...)

### ISSUE THREAD

**Issue by nathanafox-us** [nathanafox-us/foxy-sensors#7]
## New Feature
The user should be able to view/update their account details. 

## Todo:
- [x] The user sees/ can change their display name
- [x] The user has the option to update their password
    - [x] Protect the user with MFA
